### Task 1

In [ ]:
### Task 1.1

class Matrix:
    def __init__(self,m,n):
        self.__buffer = [[ None for n in range(n)] for _ in range(m)]
        self.__m = m
        self.__n = n
#[3]
    def get_dimension(self):
        return (self.__m, self.__n)
#[1]
    def __repr__(self):
        ret="["
        for r in range(self.__m):
            ret+="\n "
            for c in range(self.__n):
                ret+=f"{str(self.__buffer[r][c]):^4} "
        return ret +"\n]"
#[2]
    def get_value(self, r, c):
        if (0 < r <= self.__m) and (0 < c <= self.__n):  
            return self.__buffer[r-1][c-1]
        else:
            raise Exception("row,column error")
#[1]
    def set_value(self, r,c,value):
        self.__buffer[r-1][c-1] = value
#[1]
    def get_row(self, r):
        if 0 < r <= self.__m :
            return self.__buffer[r-1][:] ## return a copy not a ref
        else:
            raise Exception("row error")
#[1] -
    def set_row(self, r, vector): 
        if len(vector) == self.__n and 0 < r <= self.__m :
            self.__buffer[r-1] = vector[:] ##  update with a copy of vector
        else:
            raise (Exception("Vector or row number length does not match matrix dimension"))
#[1]
    def get_column(self, c):
        if 0 < c <= self.__n:
            ret = []
            for r in range(self.__m):
                ret.append(self.__buffer[r][c-1])
            return ret
        else:
            raise(Exception("column error"))       
#[2]
    def set_column(self, c, vector): 
        if len(vector) == self.__m and 0 < c <= self.__n:
            for r in range(self.__m):
                self.__buffer[r][c-1] = vector[r]
        else:
            raise (Exception("Vector length or column number does not match matrix dimension"))
#[2]

In [ ]:
### Task 1.2
A = Matrix(2,2)
A.set_row(1,[1,2])
A.set_row(2,[3,4])
print(A)
#[1]
B=Matrix(1,3)
B.set_row(1,[5,6,7])
print(B) 
#[1]
C=Matrix(3,1)
C.set_column(1,[9,8,7])
print(C)
#[1]
D=Matrix(0,0)
print(D)
E=Matrix(2,2)
E.set_row(1,[1,2])
E.set_row(2,[3])
print(E)

[
  1    2   
  3    4   
]
[
  5    6    7   
]
[
  9   
  8   
  7   
]
[
]


Exception: Vector or row number length does not match matrix dimension

In [ ]:
### Task 1.3 [2]

def dot_product(A:list, B:list) -> int:
    if len(A) != len(B): #[1]
        raise Exception("Dimensions not the same")
    else:
        ret=0
        for i in range(len(A)):#[1]
            ret += A[i]*B[i]
    return ret


In [ ]:
## 1.4 [1]
dot_product([11,13,5], [21,44,26])

In [ ]:
### Task 1.5 [2]

def transpose(M: Matrix)-> Matrix:
    row_len, col_len = M.get_dimension() 
    ret_m = Matrix(col_len,row_len ) #[1]
    for col in range(1,col_len+1):
        ret_m.set_row(col,M.get_column(col)) #[2]
    return ret_m



In [ ]:
m = Matrix(2,3)
m.set_column(1,[1,2])
m.set_column(2,[3,4])
m.set_column(3,[5,6])
print(m)
m_t = transpose(m)
print(m_t)

[
  1    3    5   
  2    4    6   
]
[
  1    2   
  3    4   
  5    6   
]


In [ ]:
print( m, m_t)
print( m_multiply(m, m_t))

In [ ]:
### Task 1.6 [8]
'''
//complete algorithm
new_matrix = Matrix(m,p)
FOR row = 1 to _ DO
 new_row = List()
 FOR col = 1 to _ DO
  row_from_A = A.get_row(row)
  col_from_B = B.get_col(col))
  result = dot_product(row_from_A, col_from_B)
  APPEND result to new_row     
 new_matrix.set_row(row,new_row)
'''

def m_multiply(A:Matrix,B:Matrix)->Matrix:
    m = A.get_dimension()[0]
    n = A.get_dimension()[1]
    p = B.get_dimension()[1]
    #[1]

    if  B.get_dimension()[0] != n:
        raise(Exception("Invalid dimensions"))
    else:
        ret = Matrix(m, p) #[1]
        for i in range(1,m+1): #[1]
            new_row = []
            row_from_A = A.get_row(i) #[1]
            for j in range(1,p+1): #[1]
                col_from_B = B.get_column(j)#[1]
                new_row.append( dot_product(row_from_A, col_from_B) )
            ret.set_row(i,new_row) #[1]
        return ret

In [ ]:
print( m_multiply(B,C))

In [ ]:
A= Matrix(3,3)
for row,vector in enumerate([[1,2,3],[4,5,6],[7,8,9]],1):
    A.set_row(row,vector)
print(A)
B=Matrix(3,2)
for row,vector in enumerate([[9,8],[6,5],[4,3]],1):
    B.set_row(row,vector)
print(B)
print( m_multiply(A,B))


[
  1    2    3   
  4    5    6   
  7    8    9   
]
[
  9    8   
  6    5   
  4    3   
]
[
  33   27  
  90   75  
 147  123  
]


In [ ]:
import numpy as np

array1=np.array([[1,2,3],[4,5,6],[7,8,9]])  
array2=np.array([[9,8],[6,5],[4,3]])  
print(f"{array1} x {array2} =")
result=np.dot(array1,array2)  
print(result) 

[[1 2 3]
 [4 5 6]
 [7 8 9]] x [[9 8]
 [6 5]
 [4 3]] =
[[ 33  27]
 [ 90  75]
 [147 123]]
